### ISSUE TITLE
[Suggestion] Iterable

### ISSUE THREAD

**Issue by GoodluckH** [adamhooper/js-priority-queue#14]
As title suggests, it would be very helpful to implement some iterators so that users can loop through items ordered by the comparator.

**Comment by adamhooper** [comment]
Thank you for your interest.

The only iterator is `.dequeue()`. And that's the way it's going to stay.

By definition, the only way to find all sorted elements in a priority queue is to remove them. This library isn't the place for a `.toArray()` or `[Symbol.iterator]` or any other such functions. Such functions would do more harm than good because A) users would call them not expecting them to clear the priority queue; and B) users might apply `js-priority-queue` to their problems where `Array` is a better fit.

Note that Java's `PriorityQueue` does have `iterator()` and `toArray()` ... and they are _not ordered_. Java's behavior is confusing. This library's behavior won't be.
