### ISSUE TITLE
It'll be great to support updating items already in the queue

### ISSUE THREAD

**Issue by svpino** [adamhooper/js-priority-queue#7]
So imagine I'd like to use this queue to implement a cache. I want to evicts entries from the cache using the number of hits each item has had (LFU strategy). 

The only thing that prevents me using this queue is that I need a way to update the number of hits in the queue.

It'll be awesome if I can access a specific item from the queue using its key.

**Comment by adamhooper** [comment]
Have you been reading something like http://stackoverflow.com/a/26584910? It's completely wrong. The person who posted it assumed (incorrectly) that priority-queue operations are free. In fact, modifying an item would cost O(lg n).

You can implement an LFU cache with O(1) complexity using linked lists and a hash, according to http://dhruvbird.com/lfu.pdf. An implementation: https://github.com/kapouer/node-lfu-cache.

js-priority-queue is rooted in academia. I won't change it to support operations that don't relate to priority queues.

**Comment by svpino** [comment]
Thanks for answering back. 

You certainly don't have to change it at all :) 

No, I wasn't reading Stack Overflow when I posted the request. Also, I'm not assuming that priority-queue operations are free. 

The fact that updates are O(lg n) makes it way faster that updating a queue that doesn't support updates. Don't you think?

Regardless of the use of the queue, I was just pointing out that having the ability to modify items already in the queue is a good thing to have. Having an immutable queue limits its usage to those problems that don't need updates. Academia doesn't dictate whether a priority-queue should be immutable.

Anyway, thanks.

**Comment by adamhooper** [comment]
js-priority-queue already lets you modify elements after you've added them. For instance:

```javascript
var queue = new PriorityQueue({ comparator: function(a, b) {
  return a.index - b.index;
}});

var item = { index: 1, mutableData: 'foo' };

queue.queue(item);
item.mutableData = 'bar'; // mutated the item after adding it to the queue
```

As long as you don't change the sort order (`item.index` in this case), everything will be fine. If you do change the sort order, you'll get undefined behavior.

And yes, you're completely right that having an immutable queue limits the set of problems it can solve. That's the whole point. If you want to solve more problems, use the underlying data structure -- usually a Heap.

Consider these (or other) data structures:

* AVL tree
* Binary tree
* B-tree
* Red-black tree
* Heap
* B-Heap

I've implemented a few of these in JavaScript (Binary Tree, Red-black tree, Heap, B-Heap). I've learned that Array is often faster than any of them in JavaScript -- especially for hundreds of elements. (How large is your cache?)

In JavaScript, Array operations are very fast while indirection (i.e., walking the nodes of a binary tree) is rather slow. Inserting an item into a binary heap of size 200 is usually slower than calling `Array.prototype.push()` followed by `Array.prototype.sort()` (assuming the comparator is quick).

Most of those O(lg n) data structures are terrible for cache-strategy implementations. Caches tend to mutate objects often and evict them rarely, so mutations should be very fast. Caches provide a unique ordering guarantee, too: in a given operation, only one counter can change, and it can only change by 1. That means the invariant, "the data structure stays sorted" can boil down to an Array swap (or no-op) for every access.

If I were you, I'd use Array+Hash. I'd start by maintaining an *unsorted* Array: `evict()` would just call `Array.prototype.sort()` and then `Array.prototype.pop()`. That might be fast enough.

If that isn't fast enough, I'd figure out how to keep the Array sorted each time a counter is incremented, using a swap operation. Unlike http://dhruvbird.com/lfu.pdf, this wouldn't be O(1) -- my idea uses a single Array to represent their doubly-linked list of singly-linked lists. But it's the same algorithm, and I think it would be faster in practice because it plays to the JavaScript interpreter's strengths.

**Comment by svpino** [comment]
Thanks Adam!

No worries. I don't need a JavaScript implementation for a cache. I've been working for the past weeks in several cache implementations in C, but while googling about the topic I stumbled on your library which looks very good.

I understand your explanation about performance on Array vs Other. Assuming a 100k entry cache, do you still think `Array.sort` + `Array.pop` is faster than a priority queue with O(lg n) updates? In JavaScript it might very well be the case, I'm not sure. I know that in C a linear array doesn't cut it.

So when I posted the first request, I was thinking about an update method in the priority-queue to update the item.index. The beauty of this is that the behavior of the queue doesn't change at all because you won't be making it worse for people who don't need updates, but you'll be providing the possibility of updating the priority for those who need it.

Anyway, I understand your point of view.

Great work maintaining this library!

**Comment by adamhooper** [comment]
Thanks for the kudos :).

In response to your question: a priority queue doesn't actually have any running-time guarantees. It's an interface, not an implementation.

That's actually why I made this library: to pick an implementation. Check http://jsperf.com/js-priority-queue-queue-dequeue/10 for my findings. At 100k entries, in JavaScript, on my Chrome beta machine, with a trivial comparison operator, heap pop+insert is 10x faster than Array pop+splice.

(The slower the comparison operator, the better the heap will perform -- it always does fewer comparisons.)

Then again, in JavaScript, "100k" is shorthand for "let's investigate other programming languages." :)
